### PR TITLE
fix log errors for private topic plugin

### PR DESCRIPTION
**Pull request by oliver-walker-hms**

### CODE REVIEW

**Comment by TomKimsey** [comment]
@oliver-walker-hms & @dbe-hms  what is that status of this?

**Comment by oliver-walker-hms** [comment]
The status is lost in time. Let's get this added

**Comment by TomKimsey** [comment]
@oliver-walker-hms do you want to solve the merge conflict?

**Comment by oliver-walker-hms** [comment]
meetings about to start, I will later in the morning

**Comment by TomKimsey** [comment]
@oliver-walker-hms I fixed it, just need you to make sure the fix is correct.

**Comment by oliver-walker-hms** [comment]
@TomKimsey  that looks right to me

**Pull request merged**
